# credentials 코드 받기
POST http://localhost:9090/authorization/credentials
Content-Type: application/json

{
  "clientId": "testClientId",
  "secret": "testSecret"
}

###

# credentials 코드 받기
GET http://localhost:9090/authorization/credentials?clientId=testClientId&secret=testSecret

###