spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 953426438615-b32ulljr2sbqsicf22dv48kju2ck75ra.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: 클라이언트ID
            client-secret: 클라이언트Secret
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize # 네아로 인증 요청 ( 콜백_URL 필요 )
            token_uri: https://nid.naver.com/oauth2.0/token # 접근 토큰 발급 요청
            user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 프로필 조회
            user_name_attribute: response # 조회시 응답 형태 속성
