# Not required
GET http://localhost:8080/students
Content-Type: application/json

###

# Not required
GET http://localhost:8080/students/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzM2OTEyMjQsInVzZXJfbmFtZSI6InVzZXJAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6Ikl4aHpVTUNqRFdNbVN6VUFvSTJLeEd5Z2tYYyIsImNsaWVudF9pZCI6InRlc3RDbGllbnRJZCIsInNjb3BlIjpbInJlYWQiXX0.paJVBKL2wKHjbmWk0IfbOx66b0zTDkI4gDAJT1SCbPI

###

# @Secured("ROLE_USER")
POST http://localhost:8080/students
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzM2OTMxNjgsInVzZXJfbmFtZSI6InVzZXJAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IlI4YjE2V0F5MTJlT1ZOQnNFbUpnRm9ZckFJcyIsImNsaWVudF9pZCI6InRlc3RDbGllbnRJZCIsInNjb3BlIjpbInJlYWQiXX0.7IfGII3ynURT5tkWiUXuIO-pBO1BJjadw4QPwcAYJCU

{
  "name": "john",
  "grade": 2,
  "age": 18,
  "hobbies": ["soccer"]
}

###

# @PreAuthorize("#oauth2.hasScope('write')")
PUT http://localhost:8080/students/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzM2OTcwMjgsInVzZXJfbmFtZSI6InVzZXJAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjJLRExXUm9pTXI3SlNGQ1VoSjJtd0Utd2U2TSIsImNsaWVudF9pZCI6InRlc3RDbGllbnRJZCIsInNjb3BlIjpbInJlYWQiXX0.oe6iDw1DeQtjbPTkVvZiWyR8NdB1ckfAcctbc71TxGg

{
  "name": "john",
  "grade": 2,
  "age": 18,
  "hobbies": ["soccer"]
}

###

# @Secured("ROLE_ADMIN")
DELETE http://localhost:8080/students/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzM2OTcwMjgsInVzZXJfbmFtZSI6InVzZXJAZ21haWwuY29tIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjJLRExXUm9pTXI3SlNGQ1VoSjJtd0Utd2U2TSIsImNsaWVudF9pZCI6InRlc3RDbGllbnRJZCIsInNjb3BlIjpbInJlYWQiXX0.oe6iDw1DeQtjbPTkVvZiWyR8NdB1ckfAcctbc71TxGg

###
